# Generated by Django 4.2 on 2026-05-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề bài viết')),
                ('anh_dai_dien', models.ImageField(upload_to='blog_images/', verbose_name='Ảnh bài viết')),
                ('mo_ta_ngan', models.TextField(max_length=500, verbose_name='Mô tả ngắn')),
                ('noi_dung', models.TextField(help_text='Hỗ trợ nhập mã HTML', verbose_name='Nội dung bài viết')),
                ('hien_thi', models.BooleanField(default=True, verbose_name='Hiện bài viết')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('seo_title', models.CharField(blank=True, help_text='Tối đa 70 ký tự', max_length=70, verbose_name='Tiêu đề trang (SEO)')),
                ('seo_description', models.TextField(blank=True, help_text='Tối đa 320 ký tự', max_length=320, verbose_name='Thẻ mô tả (SEO)')),
                ('duong_dan_alias', models.SlugField(blank=True, help_text='Để trống hệ thống sẽ tự tạo từ Tiêu đề', max_length=255, unique=True, verbose_name='Đường dẫn / Alias')),
            ],
            options={
                'verbose_name': 'Bài viết Blog',
                'verbose_name_plural': 'Quản lý Bài viết Blog',
                'ordering': ['-ngay_dang'],
            },
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tên dự án')),
                ('phan_loai', models.CharField(choices=[('M7.5', 'M7.5 SERIES'), ('NANO', 'NANO SERIES'), ('JUMBO', 'JUMBO SERIES')], default='M7.5', max_length=20, verbose_name='Dòng sản phẩm')),
                ('link_youtube', models.URLField(blank=True, help_text='Ví dụ: https://www.youtube.com/embed/...', null=True, verbose_name='Đường dẫn YouTube')),
                ('sap_ra_mat', models.BooleanField(default=False, verbose_name='Dự án sắp ra mắt (Chưa có video)')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Video Phóng sự',
                'verbose_name_plural': 'Quản lý Video Phóng sự',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
