# Generated by Django 4.2.15 on 2026-05-20 08:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_pham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tac_gia',
            field=models.CharField(default='Ban Giám Đốc', help_text='Tên người viết bài', max_length=100, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='article',
            name='noi_dung',
            field=ckeditor.fields.RichTextField(verbose_name='Nội dung bài viết'),
        ),
    ]
