# Generated by Django 6.0.5 on 2026-05-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_pham', '0002_article_tac_gia_alter_article_noi_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyTuVan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('tinh_thanh', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('da_lien_he', models.BooleanField(default=False, verbose_name='Đã liên hệ')),
            ],
            options={
                'verbose_name': 'Đăng ký tư vấn',
                'verbose_name_plural': 'Quản lý Đăng ký tư vấn',
                'ordering': ['-ngay_dang_ky'],
            },
        ),
    ]
