# Generated by Django 6.0.5 on 2026-06-18 04:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_pham', '0004_videoproject_tiktok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='noi_dung',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung bài viết'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='link_youtube',
            field=models.URLField(blank=True, help_text='Dán link YouTube (chọn khi nền tảng là YouTube). Vd: https://www.youtube.com/watch?v=...', null=True, verbose_name='Đường dẫn YouTube'),
        ),
    ]
